### ISSUE TITLE
Please put downloads on GitHub Releases, not in the git repository

### ISSUE THREAD

**Issue by probonopd** [Nowalon/v-saver#3]
Please put downloads on [GitHub Releases](https://github.com/Nowalon/v-saver/releases), not in the git repository.

Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1547

**Comment by Nowalon** [comment]
now builds downloads are stored with [Git LFS](https://git-lfs.github.com/)

**Comment by Nowalon** [comment]
now builds downloads are stored with [Git LFS](https://git-lfs.github.com/)

**Comment by probonopd** [comment]
Why not in https://github.com/Nowalon/v-saver/releases?
